services:
  - type: web
    name: clinovo-site-feasibility
    env: node
    buildCommand: npm install && npm rebuild
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.11.0
