-- ==========================================================================
-- CLINOVO SITE FEASIBILITY PORTAL - SQLITE 3 DATABASE DUMP
-- Generated: 2026-08-07T06:02:39.494Z
-- ==========================================================================

BEGIN TRANSACTION;

-- -------------------------------------------------------------------------
-- TABLE: sites
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sites (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  number TEXT,
  country TEXT,
  pi TEXT,
  status TEXT DEFAULT 'pending',
  rate REAL DEFAULT 3.0,
  total INTEGER DEFAULT 30,
  weeks INTEGER DEFAULT 12,
  scores_json TEXT,
  notes TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- -------------------------------------------------------------------------
-- TABLE: questionnaires
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS questionnaires (
  id TEXT PRIMARY KEY,
  site_id TEXT,
  protocol_number TEXT,
  protocol_title TEXT,
  sponsor TEXT,
  tumor_type TEXT,
  line_of_therapy TEXT,
  answers_json TEXT,
  scores_json TEXT,
  overall_score INTEGER,
  submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- -------------------------------------------------------------------------
-- TABLE: questionnaire_modules
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS questionnaire_modules (
  module_number TEXT PRIMARY KEY,
  module_title TEXT NOT NULL,
  kicker TEXT,
  description TEXT,
  fields_json TEXT NOT NULL
);

-- -------------------------------------------------------------------------
-- DATA: questionnaire_modules (12 Roles & Questions)
-- -------------------------------------------------------------------------
INSERT INTO questionnaire_modules (module_number, module_title, kicker, description, fields_json) VALUES ('01', 'Study Information', 'Header · 01 / 12', 'Core protocol identifiers for this feasibility record.', '[{"id":"protocolNumber","type":"text","label":"Protocol number"},{"id":"protocolTitle","type":"text","label":"Protocol title"},{"id":"sponsor","type":"text","label":"Sponsor / CRO"},{"id":"tumorType","type":"text","label":"Tumor type / indication"},{"id":"lineOfTherapy","type":"multiselect","label":"Line of therapy","options":["1L","2L","3L+","Adjuvant","Neoadjuvant","Maintenance"]},{"id":"blinding","type":"select","label":"Randomization / design","options":["Open-label","Single-blind","Double-blind"]},{"id":"arms","type":"text","label":"Number of treatment arms"},{"id":"siteName","type":"text","label":"Site name"},{"id":"siteNumber","type":"text","label":"Site number"},{"id":"country","type":"text","label":"Country"},{"id":"completedBy","type":"text","label":"Completed by (name / role)"}]');
INSERT INTO questionnaire_modules (module_number, module_title, kicker, description, fields_json) VALUES ('02', 'Site & Investigator', 'Section 1 · 02 / 12', 'Institution, PI, and study team qualifications.', '[{"id":"institution","type":"text","label":"Institution / site name and address"},{"id":"siteType","type":"text","label":"Site type","hint":"e.g., academic medical center, community hospital, dedicated research site"},{"id":"piName","type":"text","label":"Principal Investigator (PI) name and specialty"},{"id":"piLicense","type":"text","label":"PI medical license / registration number and expiry"},{"id":"piBoard","type":"text","label":"PI board certification","hint":"e.g., Medical Oncology, Hematology-Oncology, Surgical Oncology, Radiation Oncology"},{"id":"subInv","type":"text","label":"Sub-investigator(s) name(s) and specialty"},{"id":"coordinators","type":"text","label":"Study coordinator(s) / CRC(s) name(s)"},{"id":"pharmacist","type":"text","label":"Pharmacist responsible for investigational product (IP)"},{"id":"primaryContact","type":"text","label":"Primary contact name, phone, and email"},{"id":"piYears","type":"text","label":"Years PI has been in independent clinical practice"},{"id":"piTrials","type":"text","label":"Number of clinical trials PI has conducted as PI (total / active)"},{"id":"piPhase3Onc","type":"text","label":"Number of Phase III oncology trials PI has conducted as PI"},{"type":"divider","label":"Investigator & staff qualifications"},{"id":"q_gcpPI","type":"yesno","label":"Does the PI hold current Good Clinical Practice (GCP) training/certification?"},{"id":"q_gcpStaff","type":"yesno","label":"Do all sub-investigators and coordinators hold current GCP certification?"},{"id":"q_cv","type":"yesno","label":"Is the PI''s CV current, signed, and dated within the last 2 years?"},{"id":"q_delegation","type":"yesno","label":"Does the site have documented delegation-of-duties procedures?"},{"id":"q_dedicated","type":"yesno","label":"Is dedicated research staff (not solely clinical staff) available for this study?"},{"id":"q_audit","type":"yesno","label":"Has the PI or site been the subject of a regulatory audit finding, warning letter, or debarment action?","hint":"if yes, explain in comment"}]');
INSERT INTO questionnaire_modules (module_number, module_title, kicker, description, fields_json) VALUES ('03', 'Tumor Board', 'Section 1.2 · 03 / 12', 'Multidisciplinary tumor board (MDT) infrastructure.', '[{"id":"q_mdtHeld","type":"yesno","label":"Does the site hold a regular multidisciplinary tumor board (surgical, medical, radiation oncology, pathology, radiology)?","hint":"state frequency in comment"},{"id":"q_mdtPI","type":"yesno","label":"Is the PI or a sub-investigator a regular, active participant in the tumor board?"},{"id":"q_mdtProcess","type":"yesno","label":"Is there a documented process for identifying trial-eligible patients at tumor board?"}]');
INSERT INTO questionnaire_modules (module_number, module_title, kicker, description, fields_json) VALUES ('04', 'Patient Population', 'Section 2 · 04 / 12', 'Accrual potential against the fixed comparator arm.', '[{"id":"newDx","type":"text","label":"Estimated number of new patients diagnosed with this tumor type per year at this site"},{"id":"eligibleMonth","type":"text","label":"Estimated number of patients per month meeting the line-of-therapy / disease-stage criteria"},{"id":"biomarkerPrev","type":"text","label":"Estimated prevalence of required biomarker(s) in the local population","hint":"e.g., % PD-L1+, HER2+, EGFR-mutant, MSI-H"},{"id":"screenFail","type":"text","label":"Anticipated screen-failure rate and primary reasons"},{"id":"enrollRate","type":"text","label":"Projected enrollment rate (patients per month)"},{"id":"totalEnroll","type":"text","label":"Total projected enrollment over the recruitment period"},{"id":"idSource","type":"text","label":"Primary source(s) of patient identification","hint":"e.g., tumor board, referral network, molecular tumor board, registry"},{"id":"competing","type":"text","label":"Competing trials currently enrolling in the same tumor type / line of therapy at this site"},{"id":"retention","type":"text","label":"Historical retention rate for long-term oncology follow-up (survival, PFS) at this site"},{"type":"divider","label":"Recruitment capability"},{"id":"q_referral","type":"yesno","label":"Does the site have an established referral network feeding this indication?"},{"id":"q_reflex","type":"yesno","label":"Is local or reflex biomarker/companion diagnostic testing available to pre-screen patients?"},{"id":"q_diverse","type":"yesno","label":"Does the site have experience recruiting from diverse or underrepresented populations, if required?"},{"id":"q_realistic","type":"yesno","label":"Is there a realistic plan to reach the enrollment target within the sponsor''s competitive-enrollment timeline?"},{"id":"q_soc","type":"yesno","label":"Does the site routinely use the comparator / standard-of-care regimen specified in the protocol?"},{"id":"q_survival","type":"yesno","label":"Does the site have a process for capturing long-term survival status after discontinuation or study closure?"}]');
INSERT INTO questionnaire_modules (module_number, module_title, kicker, description, fields_json) VALUES ('05', 'Facilities & Equipment', 'Section 3 · 05 / 12', 'Physical infrastructure to support trial conduct.', '[{"id":"q_consent","type":"yesno","label":"Does the site have adequate private space for informed consent discussions?"},{"id":"q_infusion","type":"yesno","label":"Does the site have a dedicated infusion suite with sufficient chair/bed capacity for added study volume?","hint":"state number of chairs/beds in comment"},{"id":"q_crash","type":"yesno","label":"Is emergency resuscitation equipment (crash cart / AED) available on-site or immediately accessible?"},{"id":"q_admit","type":"yesno","label":"Is there rapid access to emergency care and inpatient admission for treatment-related toxicity?"},{"id":"q_radTx","type":"yesno","label":"Does the site have on-site or rapidly accessible radiation therapy, if required by protocol?"},{"id":"q_ipStorage","type":"yesno","label":"Does the site have refrigerated/frozen storage with continuous temperature monitoring for IP?"},{"id":"q_backupPower","type":"yesno","label":"Does the site have back-up power supply for storage equipment (e.g., generator)?"},{"id":"q_secureStorage","type":"yesno","label":"Does the site have secure, locked storage for IP and study documents?"},{"id":"q_centrifuge","type":"yesno","label":"Is a centrifuge and appropriate equipment available for biomarker/PK sample processing?"},{"id":"q_imaging","type":"yesno","label":"Does the site have CT, MRI, and/or PET capability meeting RECIST 1.1 requirements on-site?","hint":"specify modalities in comment"},{"id":"q_radiologist","type":"yesno","label":"Is there a dedicated or trained radiologist for independent tumor response assessment, if required?"},{"id":"q_freezer","type":"yesno","label":"Is a -20°C / -70°C freezer available on-site for biomarker/translational sample storage?"},{"id":"q_internet","type":"yesno","label":"Does the site have reliable internet connectivity for EDC and central imaging upload systems?"}]');
INSERT INTO questionnaire_modules (module_number, module_title, kicker, description, fields_json) VALUES ('06', 'Pharmacy & IP', 'Section 4 · 06 / 12', 'Investigational product handling and hazardous-drug safety.', '[{"id":"q_hazPharmacy","type":"yesno","label":"Does the site have a licensed oncology/research pharmacy with hazardous-drug (cytotoxic) handling certification?"},{"id":"q_bsc","type":"yesno","label":"Does the pharmacy have a certified biological safety cabinet (Class II) for hazardous drug compounding?"},{"id":"q_ipAccountability","type":"yesno","label":"Is IP accountability (receipt, dispensing, return, destruction) managed per GCP and sponsor requirements?"},{"id":"q_unblinding","type":"yesno","label":"Does the pharmacy have experience with randomized / blinded study drug procedures and unblinding SOPs?"},{"id":"q_bsaDosing","type":"yesno","label":"Does the pharmacy have experience with weight- or BSA-based dosing and dose modifications for toxicity?"},{"id":"q_tempExcursion","type":"yesno","label":"Is there a validated process for temperature excursion reporting and deviation management?"},{"id":"q_compounding","type":"yesno","label":"Does the site have capability for IP compounding, reconstitution, or infusion admixture, if required?"},{"id":"q_usp800","type":"yesno","label":"Is pharmacy staff trained in USP <800> or equivalent hazardous drug safe-handling standards?"}]');
INSERT INTO questionnaire_modules (module_number, module_title, kicker, description, fields_json) VALUES ('07', 'Lab, Pathology & Biomarkers', 'Section 5 · 07 / 12', 'Testing, tissue access, and specimen logistics.', '[{"id":"localLab","type":"text","label":"Local laboratory name and CLIA / accreditation number (or equivalent)"},{"id":"centralLab","type":"text","label":"Central laboratory experience","hint":"name central labs previously used, if any"},{"id":"pathLab","type":"text","label":"On-site or affiliated pathology laboratory name and accreditation"},{"id":"sampleHandling","type":"text","label":"Sample processing, storage, and shipping capabilities","hint":"blood, tissue, FFPE blocks"},{"id":"safetyTAT","type":"text","label":"Turnaround time for local safety labs"},{"id":"biomarkerTAT","type":"text","label":"Turnaround time for local biomarker/companion diagnostic testing, if applicable"},{"type":"divider","label":"Tissue & testing capability"},{"id":"q_labAccred","type":"yesno","label":"Does the local laboratory hold current accreditation/certification?"},{"id":"q_tissueAccess","type":"yesno","label":"Does the site have access to archival or fresh tumor tissue meeting protocol specimen requirements?"},{"id":"q_cdx","type":"yesno","label":"Is central or local biomarker/companion diagnostic testing available for required stratification factors?"},{"id":"q_researchBiopsy","type":"yesno","label":"Does the site have experience obtaining pre-treatment and on-treatment research biopsies, if required?"},{"id":"q_shipping","type":"yesno","label":"Does the site have experience shipping tissue and blood samples to a central laboratory (dry ice / ambient)?"},{"id":"q_courier","type":"yesno","label":"Is a 24-hour or rapid courier service available for sample shipment, if required?"}]');
INSERT INTO questionnaire_modules (module_number, module_title, kicker, description, fields_json) VALUES ('08', 'Safety & Toxicity', 'Section 5A · 08 / 12', 'Adverse event management and response assessment.', '[{"id":"q_ctcae","type":"yesno","label":"Is staff trained in CTCAE grading and management of study-drug-related toxicities (e.g., irAEs, infusion reactions)?"},{"id":"q_escalation","type":"yesno","label":"Does the site have a documented escalation pathway for Grade 3+ adverse events, including after-hours coverage?"},{"id":"q_oncall","type":"yesno","label":"Is a 24/7 on-call PI or sub-investigator available for urgent safety issues?"},{"id":"q_specialists","type":"yesno","label":"Does the site have access to specialists for anticipated toxicities (e.g., endocrinology, pulmonology, cardiology)?"},{"id":"q_recist","type":"yesno","label":"Does the site have experience conducting tumor response assessments per RECIST 1.1 or protocol-specified criteria?"},{"id":"q_saeReporting","type":"yesno","label":"Is there a defined process for expedited SAE / SUSAR reporting to sponsor and IRB/IEC within required timelines?"},{"id":"q_dsmb","type":"yesno","label":"Does the site have experience with studies overseen by a DSMB / IDMC, including interim analyses?"}]');
INSERT INTO questionnaire_modules (module_number, module_title, kicker, description, fields_json) VALUES ('09', 'Regulatory & Experience', 'Section 6 · 09 / 12', 'Ethics oversight and prior trial track record.', '[{"id":"irb","type":"text","label":"IRB / Independent Ethics Committee (IEC) of record"},{"id":"irbTAT","type":"text","label":"Typical IRB/IEC initial review turnaround time"},{"id":"oncTrials3y","type":"text","label":"Number of industry-sponsored oncology trials conducted in the last 3 years"},{"id":"phase3Trials3y","type":"text","label":"Number of Phase III randomized oncology trials conducted in the last 3 years"},{"id":"tumorTrials3y","type":"text","label":"Number of trials in this specific tumor type conducted in the last 3 years"},{"id":"priorSponsors","type":"text","label":"Names of sponsors/CROs the site has worked with previously"},{"id":"sivToFPI","type":"text","label":"Average time from Site Initiation Visit to first patient enrolled (historical)"}]');
INSERT INTO questionnaire_modules (module_number, module_title, kicker, description, fields_json) VALUES ('10', 'Data Management & Technology', 'Section 7 · 10 / 12', 'EDC, ePRO, and technical readiness.', '[{"id":"q_edc","type":"yesno","label":"Does the site have prior experience with electronic data capture (EDC) systems?"},{"id":"q_epro","type":"yesno","label":"Does the site have experience with ePRO or wearable devices, if required?"},{"id":"q_ehr","type":"yesno","label":"Is the EHR system compatible with source-data verification requirements?"},{"id":"q_itSupport","type":"yesno","label":"Does the site have IT support available for study-related technology issues?"},{"id":"q_part11","type":"yesno","label":"Are validated / 21 CFR Part 11-compliant computer systems used for study data?"}]');
INSERT INTO questionnaire_modules (module_number, module_title, kicker, description, fields_json) VALUES ('11', 'Budget, Contracts & Timelines', 'Section 8 · 11 / 12', 'Administrative readiness and start-up pace.', '[{"id":"contractOwner","type":"text","label":"Institution / department responsible for contract and budget negotiation"},{"id":"contractTAT","type":"text","label":"Typical timeline for contract execution once terms are agreed"},{"id":"indirectCost","type":"text","label":"Does the site require a separate institutional overhead / indirect cost rate?"},{"id":"startupTimeline","type":"text","label":"Anticipated start-up timeline (contract execution to first patient enrolled)"},{"id":"q_timelines","type":"yesno","label":"Is the site able to meet the sponsor''s proposed study timelines?"},{"id":"q_conflict","type":"yesno","label":"Are there any anticipated conflicts of interest requiring disclosure?"},{"id":"additionalComments","type":"textarea","label":"Additional comments"}]');
INSERT INTO questionnaire_modules (module_number, module_title, kicker, description, fields_json) VALUES ('12', 'Site Declaration', 'Section 9 · 12 / 12', 'Sign-off and sponsor / CRO review outcome.', '[{"id":"declPI","type":"text","label":"Principal Investigator name"},{"id":"declSignature","type":"text","label":"Signature","hint":"type name to represent signature in this draft; obtain a wet or e-signature on the final copy"},{"id":"declDate","type":"text","label":"Date"},{"type":"divider","label":"For sponsor / CRO use only"},{"id":"sponsorOutcome","type":"select","label":"Feasibility outcome","options":["Approved","Approved with conditions","Not approved"]},{"id":"reviewedBy","type":"text","label":"Reviewed by"},{"id":"reviewDate","type":"text","label":"Date"}]');

-- -------------------------------------------------------------------------
-- DATA: sites
-- -------------------------------------------------------------------------
INSERT INTO sites (id, name, number, country, pi, status, rate, total, weeks, scores_json, notes, created_at) VALUES ('s1', 'Memorial Oncology Institute', '014', 'United States', 'Dr. R. Chen', 'approved', 4.2, 42, 10, '{"invSite":92,"patientPop":85,"facilities":90,"pharmacy":88,"labBiomarker":84,"safety":90,"regulatory":95,"dataTech":80,"budget":78}', 'High-volume academic center; strong tumor board and prior Phase III experience.', '2026-08-06 09:14:02');
INSERT INTO sites (id, name, number, country, pi, status, rate, total, weeks, scores_json, notes, created_at) VALUES ('s2', 'Riverside Cancer Center', '027', 'United States', 'Dr. A. Patel', 'conditional', 2.8, 25, 14, '{"invSite":74,"patientPop":70,"facilities":55,"pharmacy":52,"labBiomarker":65,"safety":68,"regulatory":72,"dataTech":60,"budget":66}', 'Pharmacy lacks Class II biosafety cabinet — hazardous drug upgrade required.', '2026-08-06 09:14:02');
INSERT INTO sites (id, name, number, country, pi, status, rate, total, weeks, scores_json, notes, created_at) VALUES ('s3', 'St. Elisabeth University Hospital', '031', 'Germany', 'Dr. M. Fischer', 'approved', 3.1, 30, 12, '{"invSite":88,"patientPop":72,"facilities":80,"pharmacy":85,"labBiomarker":90,"safety":82,"regulatory":91,"dataTech":75,"budget":70}', 'Excellent central lab & biomarker infrastructure; moderate accrual pace.', '2026-08-06 09:14:02');
INSERT INTO sites (id, name, number, country, pi, status, rate, total, weeks, scores_json, notes, created_at) VALUES ('s1786076844668', 'Submitted Clinical Site', '880', 'United States', 'Dr. Submitting PI', 'pending', 3, 30, 12, '{"invSite":0,"patientPop":0,"facilities":0,"pharmacy":100,"labBiomarker":0,"safety":0,"regulatory":0,"dataTech":60,"budget":50}', 'Submitted via Site Feasibility Questionnaire on 7/8/2026. Overall Score: 23/100.', '2026-08-07 04:27:24');
INSERT INTO sites (id, name, number, country, pi, status, rate, total, weeks, scores_json, notes, created_at) VALUES ('s1786076994873', 'Submitted Clinical Site', '605', 'United States', 'Dr. Submitting PI', 'pending', 3, 30, 12, '{"invSite":0,"patientPop":0,"facilities":0,"pharmacy":0,"labBiomarker":0,"safety":0,"regulatory":0,"dataTech":0,"budget":0}', 'Submitted via Site Feasibility Questionnaire on 7/8/2026. Overall Score: 0/100.', '2026-08-07 04:29:54');

-- -------------------------------------------------------------------------
-- DATA: questionnaires
-- -------------------------------------------------------------------------
INSERT INTO questionnaires (id, site_id, protocol_number, protocol_title, sponsor, tumor_type, line_of_therapy, answers_json, scores_json, overall_score, submitted_at) VALUES ('q1786076844668', 's1786076844668', '', '', '', '', '[]', '{"q_ipAccountability":{"v":"yes","c":""},"q_unblinding":{"v":"yes","c":""},"q_bsc":{"v":"yes","c":""},"q_hazPharmacy":{"v":"yes","c":""},"q_bsaDosing":{"v":"yes","c":""},"q_tempExcursion":{"v":"yes","c":""},"q_compounding":{"v":"yes","c":""},"q_usp800":{"v":"yes","c":""},"q_ehr":{"v":"no","c":""},"q_part11":{"v":"yes","c":""},"q_epro":{"v":"yes","c":""},"q_edc":{"v":"yes","c":""},"contractOwner":"yes","startupTimeline":"","q_timelines":{"v":"yes","c":""}}', '{"invSite":0,"patientPop":0,"facilities":0,"pharmacy":100,"labBiomarker":0,"safety":0,"regulatory":0,"dataTech":60,"budget":50}', 23, '2026-08-07 04:27:24');
INSERT INTO questionnaires (id, site_id, protocol_number, protocol_title, sponsor, tumor_type, line_of_therapy, answers_json, scores_json, overall_score, submitted_at) VALUES ('q1786076994873', 's1786076994873', '', '', '', '', '[]', '{}', '{"invSite":0,"patientPop":0,"facilities":0,"pharmacy":0,"labBiomarker":0,"safety":0,"regulatory":0,"dataTech":0,"budget":0}', 0, '2026-08-07 04:29:54');

COMMIT;
